dependencies:
  - name: nodejs
    version: ~1.10.0
    repository: '@hmctspublic'
  - name: ccd
    version: ~4.3.2
    repository: '@hmctspublic'
    tags:
      - ccd-idam-pr
  - name: xui-webapp
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: xui-webapp.enabled