tags:
  ccd-pr: true

nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

idam-pr:
  releaseNameOverride: ${SERVICE_NAME}-idam-pr
  enabled: true
  redirect_uris:
    XUI:
      - https://xui-${SERVICE_FQDN}/oauth2/callback
    CCD:
      - https://case-management-web-${SERVICE_FQDN}/oauth2redirect
    CCD Admin:
      - https://admin-web-${SERVICE_FQDN}/oauth2redirect
    divorce:
      - https://pfe-${SERVICE_FQDN}/authenticated
      - https://rfe-${SERVICE_FQDN}/authenticated
      - https://da-${SERVICE_FQDN}/authenticated
      - https://dn-${SERVICE_FQDN}/authenticated
xui-webapp:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-xui-webapp
    image: hmctspublic.azurecr.io/xui/webapp:latest
    ingressHost: xui-${SERVICE_FQDN}
    environment:
      HEALTH_CCD_COMPONENT_API: http://gateway-${SERVICE_FQDN}/health
      HEALTH_CCD_DATA_API: http://${SERVICE_NAME}-ccd-data-store-api/health
      HEALTH_TERMS_AND_CONDITIONS_API: http://xui-terms-and-conditions-${SERVICE_FQDN}.service.core-compute-preview.internal/health
      SERVICES_CCD_COMPONENT_API: http://gateway-${SERVICE_FQDN}
      SERVICES_CCD_DATA_STORE_API: http://${SERVICE_NAME}-ccd-data-store-api
      SERVICES_TERMS_AND_CONDITIONS: http://xui-terms-and-conditions-${SERVICE_FQDN}.service.core-compute-preview.internal
      JURISDICTIONS: DIVORCE

div-pfe:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-div-pfe
    image: hmctspublic.azurecr.io/div/pfe:latest
    ingressHost: pfe-${SERVICE_FQDN}
    environment:
      DECREE_NISI_FRONTEND_URL: http://${SERVICE_NAME}-div-dn

div-rfe:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-div-rfe
    image: hmctspublic.azurecr.io/div/rfe:latest
    ingressHost: rfe-${SERVICE_FQDN}

div-da:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-div-da
    image: hmctspublic.azurecr.io/div/da:latest
    ingressHost: da-${SERVICE_FQDN}
    environment:
      DECREE_NISI_FRONTEND_URL: http://${SERVICE_NAME}-div-dn
      PETITIONER_FRONTEND_URL: http://${SERVICE_NAME}-div-pfe
      RESPONDENT_FRONTEND_URL: http://${SERVICE_NAME}-div-rfe
div-dn:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-div-dn
    image: hmctspublic.azurecr.io/div/dn:latest
    ingressHost: dn-${SERVICE_FQDN}
    environment:
      DECREE_ABSOLUTE_FRONTEND_URL: http://${SERVICE_NAME}-div-da
      PETITIONER_FRONTEND_URL: http://${SERVICE_NAME}-div-pfe
      RESPONDENT_FRONTEND_URL: http://${SERVICE_NAME}-div-rfe

ccd:
  ccd:
    definitionImporter:
      enabled: false
    managementWeb:
       enabled: true
    apiGatewayWeb:
      enabled: true
    s2s:
      enabled: false
    printService:
      enabled: true

  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}

  global:
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    ccdAdminWebIngress: admin-web-${SERVICE_FQDN}
    ccdApiGatewayIngress: gateway-${SERVICE_FQDN}
    ccdCaseManagementWebIngress: case-management-web-${SERVICE_FQDN}
    postgresUsername: hmcts
    postgresPassword: hmcts
    s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

  ccd-user-profile-api:
    java:
      imagePullPolicy: Always
      enviroment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
      keyVaults: []
      environment:
        USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_admin,ccd_data,ccd_definition,divorce
      ingressHost: ccd-user-profile-api-${SERVICE_FQDN}

  ccd-data-store-api:
    java:
      imagePullPolicy: Always
      environment:
        DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DATA_STORE_IDAM_KEY: ${DATA_STORE_S2S_KEY}
        IDAM_API_BASE_URL: https://idam-api.aat.platform.hmcts.net
        IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
        IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET}
        IDAM_DATA_STORE_SYSTEM_USER_USERNAME: ${IDAM_DATA_STORE_SYSTEM_USER_USERNAME}
        IDAM_DATA_STORE_SYSTEM_USER_PASSWORD: ${IDAM_DATA_STORE_SYSTEM_USER_PASSWORD}
        CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal
      keyVaults: []
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}

  ccd-definition-store-api:
    java:
      imagePullPolicy: Always
      keyVaults: []
      environment:
        DEFINITION_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DEFINITION_STORE_IDAM_KEY: ${DEFINITION_STORE_S2S_KEY}
        DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_admin,ccd_data,divorce,ccd_gw,divorce_ccd_submission
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts
      ingressHost: ccd-definition-store-${SERVICE_FQDN}

  ccd-admin-web:
    nodejs:
      image: hmctspublic.azurecr.io/ccd/admin-web:latest
      ingressHost: admin-web-${SERVICE_FQDN}
      keyVaults: []
      environment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
        IDAM_ADMIN_WEB_SERVICE_KEY: ${ADMIN_S2S_KEY}
        IDAM_OAUTH2_AW_CLIENT_SECRET: ${ADMIN_WEB_IDAM_SECRET}
    idam-pr:
      enabled: true

  ccd-case-management-web:
    nodejs:
      devmemoryRequests: 512Mi
      devcpuRequests: "1000m"
      devmemoryLimits: 1024Mi
      devcpuLimits: "2500m"
      resources:
        requests:
          cpu: 1000m
          memory: 512Mi
      environment:
        CCD_ACTIVITY_URL: null
        DM_URL: https://gateway-${SERVICE_FQDN}/documents
        DM_URL_REMOTE: https?://(gateway-${SERVICE_FQDN}:443|dm-store-aat.service.core-compute-aat.internal)/documents
        NODE_TLS_REJECT_UNAUTHORIZED: 0
        APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
        APPINSIGHTS_ENABLED: false
      ingressHost: case-management-web-${SERVICE_FQDN}
      ingressIP: ${INGRESS_IP}
    idam-pr:
      enabled: true

  ccd-api-gateway-web:
    nodejs:
      keyVaults: []
      environment:
        IDAM_SERVICE_KEY: ${API_GATEWAY_S2S_KEY}
        IDAM_OAUTH2_CLIENT_SECRET: ${API_GATEWAY_IDAM_SECRET}
        PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
        PROXY_PRINT_SERVICE: http://ccd-case-print-service-${SERVICE_FQDN}
        ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
      ingressHost: gateway-${SERVICE_FQDN}
      ingressIP: ${INGRESS_IP}

  ccd-case-print-service:
    nodejs:
      keyVaults: []
      environment:
        IDAM_PRINT_SERVICE_KEY: ${PRINT_S2S_KEY}
      ingressHost: ccd-case-print-service-${SERVICE_FQDN}

  importer:
    userprofile:
      enabled: true
      jurisdictions:
        - DIVORCE
      users:
        - divorce_as_caseworker_beta@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_solicitor@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_bulk_scanner@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_superuser@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_la@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_admin@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_respondent_solicitor@mailinator.com|DIVORCE|DIVORCE|Submitted
      userProfileDatabaseHost: ${SERVICE_NAME}-ccd-postgres
      userProfileDatabasePort: 5432
      userProfileDatabaseUser: hmcts
      userProfileDatabasePassword: hmcts
      userProfileDatabaseName: user-profile

  postgresql:
    persistence:
      enabled: false
