nodejs:
  applicationPort: 3000
  memoryRequests: 512Mi
  memoryLimits: 1024Mi
  cpuRequests: "1000m"
  cpuLimits: "2500m"
  devmemoryRequests: 512Mi
  devcpuRequests: "1000m"
  devmemoryLimits: 1024Mi
  devcpuLimits: "2500m"
