tags:
  ccd-idam-pr: true

nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

ccd:
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}

  idam-pr:
    releaseNameOverride: ${SERVICE_NAME}-ccd-idam-pr
    redirect_uris:
      CCD:
        - https://case-management-web-${SERVICE_FQDN}/oauth2redirect
      CCD Admin:
        - https://admin-web-${SERVICE_FQDN}/oauth2redirect

  apiGateway:
    s2sKey: ${API_GATEWAY_S2S_KEY}
    idamClientSecret: ${API_GATEWAY_IDAM_SECRET}

  userProfileApi:
    authorisedServices: ccd_admin,ccd_data,ccd_definition,cmc_claim_store

  dataStoreApi:
    s2sKey: ${DATA_STORE_S2S_KEY}
    s2sAuthorisedServices: cmc_claim_store,ccd_gw

  definitionStoreApi:
    s2sKey: ${DEFINITION_STORE_S2S_KEY}
    s2sAuthorisedServices: ccd_admin,ccd_data,cmc_claim_store,ccd_gw

  caseManagementWeb:
    enabled: true # if you need access to the web ui then enable this, otherwise it won't be deployed
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0

  adminWeb:
    enabled: true # if you need access to the admin web ui then enable this, otherwise it won't be deployed
    s2sKey: ${ADMIN_S2S_KEY}
    idamClientSecret: ${ADMIN_WEB_IDAM_SECRET}
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0

  importer:
    userprofile:
      enabled: true
      jurisdictions:
        - Divorce
      users:
        - divorce_as_caseworker_beta@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_solicitor@mailinator.com|DIVORCE|DIVORCE|Submitted
      userProfileDatabaseHost: ${SERVICE_NAME}-ccd-postgres
      userProfileDatabasePort: 5432
      userProfileDatabaseUser: hmcts
      userProfileDatabasePassword: hmcts
      userProfileDatabaseName: user-profile
    definition:
      enabled: true
      image: hmcts.azurecr.io/hmcts/div-ccd-definitions:latest
      definitionFilename: ccd-config-aat.xlsx
      userRoles:
        - caseworker
        - caseworker-divorce
        - caseworker-divorce-courtadmin
        - caseworker-divorce-courtadmin_beta
        - caseworker-divorce-solicitor
        - caseworker-divorce-systemupdate
        - caseworker-divorce-bulkscan
        - caseworker-divorce-courtadmin-la
        - caseworker-divorce-superuser
