tags:
  ccd-idam-pr: true

nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

ccd:
  ccd:
    definitionImporter:
      enabled: false
    managementWeb:
      enabled: true
    apiGatewayWeb:
      enabled: true

  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}

  global:
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    ccdAdminWebIngress: admin-web-${SERVICE_FQDN}
    ccdApiGatewayIngress: gateway-${SERVICE_FQDN}
    ccdCaseManagementWebIngress: case-management-web-${SERVICE_FQDN}
    postgresUsername: hmcts
    postgresPassword: hmcts

  idam-pr:
    releaseNameOverride: ${SERVICE_NAME}-ccd-idam-pr
    redirect_uris:
      CCD:
        - https://case-management-web-${SERVICE_FQDN}/oauth2redirect
      CCD Admin:
        - https://admin-web-${SERVICE_FQDN}/oauth2redirect

  ccd-user-profile-api:
    java:
      imagePullPolicy: Always
      enviroment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
      keyVaults:
      environment:
        USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,ccd_admin

  ccd-data-store-api:
    java:
      imagePullPolicy: Always
      environment:
        DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DATA_STORE_IDAM_KEY: ${DATA_STORE_S2S_KEY}
      keyVaults:

  ccd-definition-store-api:
    java:
      imagePullPolicy: Always
      keyVaults:
      environment:
        DEFINITION_STORE_IDAM_KEY: ${DEFINITION_STORE_S2S_KEY}
        DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_admin
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts

  ccd-admin-web:
    nodejs:
      image: hmctspublic.azurecr.io/ccd/admin-web:latest
      ingressHost: admin-web-${SERVICE_FQDN}
      keyVaults:
      environment:
        IDAM_OAUTH2_AW_CLIENT_SECRET: ${ADMIN_WEB_IDAM_SECRET}
    idam-pr:
      enabled: true

  ccd-case-management-web:
    nodejs:
      ingressHost: case-management-web-${SERVICE_FQDN}
    idam-pr:
      enabled: true

  ccd-api-gateway-web:
    nodejs:
      ingressHost: gateway-${SERVICE_FQDN}
      keyVaults:
      environment:
        IDAM_OAUTH2_CLIENT_SECRET: ${API_GATEWAY_IDAM_SECRET}

  importer:
    userprofile:
      enabled: true
      jurisdictions:
        - DIVORCE
      users:
        - divorce_as_caseworker_beta@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_solicitor@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_bulk_scanner@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_superuser@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_la@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_as_caseworker_admin@mailinator.com|DIVORCE|DIVORCE|Submitted
        - divorce_respondent_solicitor@mailinator.com|DIVORCE|DIVORCE|Submitted
      userProfileDatabaseHost: ${SERVICE_NAME}-ccd-postgres
      userProfileDatabasePort: 5432
      userProfileDatabaseUser: hmcts
      userProfileDatabasePassword: hmcts
      userProfileDatabaseName: user-profile

  postgresql:
    persistence:
      enabled: false