const nonProdTabDisplayOrder = {
  History: 1,
  petitionDetails: 2,
  aosDetails: 3,
  dnDetails: 4,
  outcomeOfDnDetails: 5,
  DecreeAbsolute: 6,
  paymentDetailsCourtAdmin: 7,
  paymentDetailsCourtAdminBeta: 8,
  paymentDetailsCourtAdminLa: 9,
  documents: 10,
  confidentialPetitionerCourtAdmin: 11,
  confidentialPetitionerCourtAdminBeta: 12,
  confidentialPetitionerCourtAdminLa: 13,
  confidentialRespondentCourtAdmin: 14,
  confidentialRespondentCourtAdminBeta: 15,
  confidentialRespondentCourtAdminLa: 16,
  confidentialCoRespondentCourtAdmin: 17,
  confidentialCoRespondentCourtAdminBeta: 18,
  confidentialCoRespondentCourtAdminLa: 19,
  notes: 20,
  marriageCertificate: 21,
  coRespondent: 22,
  serviceApplication: 23,
  LinkedCase: 24,
  Language: 25,
  ConfidentialDocuments: 26,
  General: 1
};

const nonProdTabIds = [
  'History',
  'General',
  'petitionDetails',
  'aosDetails',
  'dnDetails',
  'outcomeOfDnDetails',
  'DecreeAbsolute',
  'paymentDetailsCourtAdmin',
  'paymentDetailsCourtAdminBeta',
  'paymentDetailsCourtAdminLa',
  'documents',
  'confidentialPetitionerCourtAdmin',
  'confidentialPetitionerCourtAdminBeta',
  'confidentialPetitionerCourtAdminLa',
  'confidentialRespondentCourtAdmin',
  'confidentialRespondentCourtAdminBeta',
  'confidentialRespondentCourtAdminLa',
  'confidentialCoRespondentCourtAdmin',
  'confidentialCoRespondentCourtAdminBeta',
  'confidentialCoRespondentCourtAdminLa',
  'notes',
  'marriageCertificate',
  'coRespondent',
  // 'SolicitorCoRespondent', - TODO - uncomment this when we go live with AOS pack 2
  'serviceApplication',
  'LinkedCase',
  'Language',
  'ConfidentialDocuments'
];

const prodTabDisplayOrder = {
  History: 1,
  petitionDetails: 2,
  aosDetails: 3,
  dnDetails: 4,
  outcomeOfDnDetails: 5,
  DecreeAbsolute: 6,
  paymentDetailsCourtAdmin: 7,
  paymentDetailsCourtAdminBeta: 8,
  paymentDetailsCourtAdminLa: 9,
  documents: 10,
  confidentialPetitionerCourtAdmin: 11,
  confidentialPetitionerCourtAdminBeta: 12,
  confidentialPetitionerCourtAdminLa: 13,
  confidentialRespondentCourtAdmin: 14,
  confidentialRespondentCourtAdminBeta: 15,
  confidentialRespondentCourtAdminLa: 16,
  confidentialCoRespondentCourtAdmin: 17,
  confidentialCoRespondentCourtAdminBeta: 18,
  confidentialCoRespondentCourtAdminLa: 19,
  notes: 20,
  marriageCertificate: 21,
  coRespondent: 22,
  LinkedCase: 23,
  Language: 24,
  ConfidentialDocuments: 25,
  General: 1
};

const prodTabIds = [
  'History',
  'General',
  'petitionDetails',
  'aosDetails',
  'dnDetails',
  'outcomeOfDnDetails',
  'DecreeAbsolute',
  'paymentDetailsCourtAdmin',
  'paymentDetailsCourtAdminBeta',
  'paymentDetailsCourtAdminLa',
  'documents',
  'confidentialPetitionerCourtAdmin',
  'confidentialPetitionerCourtAdminBeta',
  'confidentialPetitionerCourtAdminLa',
  'confidentialRespondentCourtAdmin',
  'confidentialRespondentCourtAdminBeta',
  'confidentialRespondentCourtAdminLa',
  'confidentialCoRespondentCourtAdmin',
  'confidentialCoRespondentCourtAdminBeta',
  'confidentialCoRespondentCourtAdminLa',
  'notes',
  'marriageCertificate',
  'coRespondent',
  // 'SolicitorCoRespondent', - TODO - uncomment this when we go live with AOS pack 2
  'LinkedCase',
  'Language',
  'ConfidentialDocuments'
];

module.exports = {
  nonProdTabDisplayOrder,
  nonProdTabIds,
  prodTabDisplayOrder,
  prodTabIds
};